using FluentAssertions;
using MediatR;
using Microsoft.Extensions.Logging;
using Moq;
using SwiftApp.ERP.Modules.Purchasing.Application.DTOs;
using SwiftApp.ERP.Modules.Purchasing.Application.Services;
using SwiftApp.ERP.Modules.Purchasing.Domain.Entities;
using SwiftApp.ERP.Modules.Purchasing.Domain.Enums;
using SwiftApp.ERP.Modules.Purchasing.Domain.Events;
using SwiftApp.ERP.Modules.Purchasing.Domain.Interfaces;
using SwiftApp.ERP.SharedKernel.Domain;
using SwiftApp.ERP.SharedKernel.Exceptions;
using Xunit;

namespace SwiftApp.ERP.Modules.Purchasing.Tests;

public class PurchaseOrderServiceTests
{
    private readonly Mock<IPurchaseOrderRepository> _orderRepo = new();
    private readonly Mock<IPurchaseOrderLineRepository> _lineRepo = new();
    private readonly Mock<ISupplierRepository> _supplierRepo = new();
    private readonly Mock<IPublisher> _publisher = new();
    private readonly Mock<ILogger<PurchaseOrderService>> _logger = new();
    private readonly PurchaseOrderService _sut;

    public PurchaseOrderServiceTests()
    {
        _sut = new PurchaseOrderService(_orderRepo.Object, _lineRepo.Object, _supplierRepo.Object, _publisher.Object, _logger.Object);
    }

    private static Supplier CreateTestSupplier() => new()
    {
        Id = Guid.NewGuid(),
        SupplierNumber = "SUP-2026-00001",
        CompanyName = "Swiss Components GmbH",
        Active = true,
        CreatedAt = DateTimeOffset.UtcNow
    };

    private static PurchaseOrder CreateTestOrder(Supplier? supplier = null, PurchaseOrderStatus status = PurchaseOrderStatus.Draft)
    {
        var s = supplier ?? CreateTestSupplier();
        return new PurchaseOrder
        {
            Id = Guid.NewGuid(),
            OrderNumber = "PO-2026-00001",
            SupplierId = s.Id,
            Supplier = s,
            Status = status,
            OrderDate = DateOnly.FromDateTime(DateTime.UtcNow),
            Currency = "CHF",
            CreatedAt = DateTimeOffset.UtcNow
        };
    }

    [Fact]
    public async Task ShouldCreateOrder_WithAutoGeneratedNumber()
    {
        var supplier = CreateTestSupplier();
        var request = new PurchaseOrderRequest(supplier.Id, null, null, "Test PO", null);

        _supplierRepo.Setup(r => r.GetByIdAsync(supplier.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(supplier);
        _orderRepo.Setup(r => r.GetMaxSequenceForYearAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(0);

        var result = await _sut.CreateAsync(request);

        result.OrderNumber.Should().StartWith("PO-");
        result.Status.Should().Be("Draft");
        _orderRepo.Verify(r => r.AddAsync(It.IsAny<PurchaseOrder>(), It.IsAny<CancellationToken>()), Times.Once);
        _publisher.Verify(p => p.Publish(It.IsAny<PurchaseOrderCreatedEvent>(), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task ShouldThrow_WhenSupplierNotFound()
    {
        var request = new PurchaseOrderRequest(Guid.NewGuid(), null, null, null, null);
        _supplierRepo.Setup(r => r.GetByIdAsync(It.IsAny<Guid>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((Supplier?)null);

        var act = () => _sut.CreateAsync(request);

        await act.Should().ThrowAsync<EntityNotFoundException>();
    }

    [Fact]
    public async Task ShouldSubmitOrder_WhenDraftWithLines()
    {
        var order = CreateTestOrder();
        order.Lines.Add(new PurchaseOrderLine { MaterialId = Guid.NewGuid(), Quantity = 10, UnitPrice = 50m, LineTotal = 500m });
        _orderRepo.Setup(r => r.GetByIdAsync(order.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(order);

        var result = await _sut.SubmitAsync(order.Id);

        result.Status.Should().Be("Submitted");
    }

    [Fact]
    public async Task ShouldThrow_WhenSubmittingNonDraftOrder()
    {
        var order = CreateTestOrder(status: PurchaseOrderStatus.Confirmed);
        _orderRepo.Setup(r => r.GetByIdAsync(order.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(order);

        var act = () => _sut.SubmitAsync(order.Id);

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "ORDER_NOT_DRAFT");
    }

    [Fact]
    public async Task ShouldConfirmOrder_WhenSubmitted()
    {
        var order = CreateTestOrder(status: PurchaseOrderStatus.Submitted);
        _orderRepo.Setup(r => r.GetByIdAsync(order.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(order);

        var result = await _sut.ConfirmAsync(order.Id);

        result.Status.Should().Be("Confirmed");
        _publisher.Verify(p => p.Publish(It.IsAny<PurchaseOrderConfirmedEvent>(), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task ShouldReceiveOrder_WhenConfirmed()
    {
        var order = CreateTestOrder(status: PurchaseOrderStatus.Confirmed);
        _orderRepo.Setup(r => r.GetByIdAsync(order.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(order);

        var result = await _sut.ReceiveAsync(order.Id);

        result.Status.Should().Be("Received");
        _publisher.Verify(p => p.Publish(It.IsAny<PurchaseOrderReceivedEvent>(), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Theory]
    [InlineData(PurchaseOrderStatus.Completed)]
    [InlineData(PurchaseOrderStatus.Cancelled)]
    public async Task ShouldThrow_WhenCancellingCompletedOrCancelled(PurchaseOrderStatus status)
    {
        var order = CreateTestOrder(status: status);
        _orderRepo.Setup(r => r.GetByIdAsync(order.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(order);

        var act = () => _sut.CancelAsync(order.Id, "reason");

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "ORDER_CANNOT_CANCEL");
    }

    [Theory]
    [InlineData(PurchaseOrderStatus.Draft)]
    [InlineData(PurchaseOrderStatus.Cancelled)]
    public async Task ShouldDeleteOrder_WhenDraftOrCancelled(PurchaseOrderStatus status)
    {
        var order = CreateTestOrder(status: status);
        _orderRepo.Setup(r => r.GetByIdAsync(order.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(order);

        await _sut.DeleteAsync(order.Id);

        _orderRepo.Verify(r => r.SoftDeleteAsync(order.Id, It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task ShouldThrow_WhenDeletingActiveOrder()
    {
        var order = CreateTestOrder(status: PurchaseOrderStatus.Confirmed);
        _orderRepo.Setup(r => r.GetByIdAsync(order.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(order);

        var act = () => _sut.DeleteAsync(order.Id);

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "ORDER_CANNOT_DELETE");
    }
}
