using FluentAssertions;
using MediatR;
using Microsoft.Extensions.Logging;
using Moq;
using SwiftApp.ERP.Modules.Accounting.Application.DTOs;
using SwiftApp.ERP.Modules.Accounting.Application.Services;
using SwiftApp.ERP.Modules.Accounting.Domain.Entities;
using SwiftApp.ERP.Modules.Accounting.Domain.Enums;
using SwiftApp.ERP.Modules.Accounting.Domain.Events;
using SwiftApp.ERP.Modules.Accounting.Domain.Interfaces;
using SwiftApp.ERP.SharedKernel.Domain;
using SwiftApp.ERP.SharedKernel.Exceptions;
using Xunit;

namespace SwiftApp.ERP.Modules.Accounting.Tests;

public class JournalEntryServiceTests
{
    private readonly Mock<IJournalEntryRepository> _entryRepo = new();
    private readonly Mock<IAccountRepository> _accountRepo = new();
    private readonly Mock<IPublisher> _publisher = new();
    private readonly Mock<ILogger<JournalEntryService>> _logger = new();
    private readonly JournalEntryService _sut;

    public JournalEntryServiceTests()
    {
        _sut = new JournalEntryService(_entryRepo.Object, _accountRepo.Object, _publisher.Object, _logger.Object);
    }

    private static Account CreateAccount(AccountType type = AccountType.Asset, decimal balance = 0m) => new()
    {
        Id = Guid.NewGuid(),
        AccountNumber = "1000",
        Name = "Cash CHF",
        AccountType = type,
        Balance = balance,
        Active = true,
        CreatedAt = DateTimeOffset.UtcNow
    };

    private static JournalEntry CreateEntry(bool posted = false, bool reversed = false)
    {
        var cashId = Guid.NewGuid();
        var revenueId = Guid.NewGuid();
        var entry = new JournalEntry
        {
            Id = Guid.NewGuid(),
            EntryNumber = "JE-000001",
            Description = "Watch sale",
            EntryDate = DateOnly.FromDateTime(DateTime.UtcNow),
            Posted = posted,
            Reversed = reversed,
            CreatedAt = DateTimeOffset.UtcNow
        };
        entry.Lines.Add(new JournalEntryLine { AccountId = cashId, Debit = 1000m, Credit = 0m, Position = 0 });
        entry.Lines.Add(new JournalEntryLine { AccountId = revenueId, Debit = 0m, Credit = 1000m, Position = 1 });
        return entry;
    }

    [Fact]
    public async Task ShouldCreateEntry_WithAutoGeneratedNumber()
    {
        var account1 = CreateAccount(AccountType.Asset);
        var account2 = CreateAccount(AccountType.Revenue);
        var request = new JournalEntryRequest("Watch sale", DateOnly.FromDateTime(DateTime.UtcNow), null, null, null,
        [
            new JournalEntryLineRequest(account1.Id, "Cash in", 1000m, 0m, null),
            new JournalEntryLineRequest(account2.Id, "Revenue", 0m, 1000m, null)
        ]);

        _accountRepo.Setup(r => r.GetByIdAsync(account1.Id, It.IsAny<CancellationToken>())).ReturnsAsync(account1);
        _accountRepo.Setup(r => r.GetByIdAsync(account2.Id, It.IsAny<CancellationToken>())).ReturnsAsync(account2);
        _entryRepo.Setup(r => r.GetNextSequenceNumberAsync(It.IsAny<CancellationToken>())).ReturnsAsync(1);
        _entryRepo.Setup(r => r.GetByIdAsync(It.IsAny<Guid>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(CreateEntry());

        var result = await _sut.CreateAsync(request);

        result.Should().NotBeNull();
        _entryRepo.Verify(r => r.AddAsync(It.IsAny<JournalEntry>(), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task ShouldThrow_WhenAccountNotFound()
    {
        var badId = Guid.NewGuid();
        var request = new JournalEntryRequest("Test", DateOnly.FromDateTime(DateTime.UtcNow), null, null, null,
        [
            new JournalEntryLineRequest(badId, "Missing", 500m, 0m, null)
        ]);

        _accountRepo.Setup(r => r.GetByIdAsync(badId, It.IsAny<CancellationToken>())).ReturnsAsync((Account?)null);

        var act = () => _sut.CreateAsync(request);

        await act.Should().ThrowAsync<EntityNotFoundException>();
    }

    [Fact]
    public async Task ShouldPostEntry_WhenBalanced()
    {
        var cashAccount = CreateAccount(AccountType.Asset, 0m);
        var revenueAccount = CreateAccount(AccountType.Revenue, 0m);
        var entry = new JournalEntry
        {
            Id = Guid.NewGuid(),
            EntryNumber = "JE-000001",
            Posted = false,
            CreatedAt = DateTimeOffset.UtcNow
        };
        entry.Lines.Add(new JournalEntryLine { AccountId = cashAccount.Id, Debit = 5000m, Credit = 0m, Position = 0 });
        entry.Lines.Add(new JournalEntryLine { AccountId = revenueAccount.Id, Debit = 0m, Credit = 5000m, Position = 1 });

        _entryRepo.Setup(r => r.GetByIdAsync(entry.Id, It.IsAny<CancellationToken>())).ReturnsAsync(entry);
        _accountRepo.Setup(r => r.GetByIdAsync(cashAccount.Id, It.IsAny<CancellationToken>())).ReturnsAsync(cashAccount);
        _accountRepo.Setup(r => r.GetByIdAsync(revenueAccount.Id, It.IsAny<CancellationToken>())).ReturnsAsync(revenueAccount);

        var result = await _sut.PostAsync(entry.Id);

        result.Posted.Should().BeTrue();
        cashAccount.Balance.Should().Be(5000m); // Asset: debit increases
        revenueAccount.Balance.Should().Be(5000m); // Revenue: credit increases
        _publisher.Verify(p => p.Publish(It.IsAny<JournalEntryPostedEvent>(), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task ShouldThrow_WhenPostingAlreadyPosted()
    {
        var entry = CreateEntry(posted: true);
        _entryRepo.Setup(r => r.GetByIdAsync(entry.Id, It.IsAny<CancellationToken>())).ReturnsAsync(entry);

        var act = () => _sut.PostAsync(entry.Id);

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "ENTRY_ALREADY_POSTED");
    }

    [Fact]
    public async Task ShouldThrow_WhenPostingUnbalancedEntry()
    {
        var entry = new JournalEntry
        {
            Id = Guid.NewGuid(),
            EntryNumber = "JE-000002",
            Posted = false,
            CreatedAt = DateTimeOffset.UtcNow
        };
        entry.Lines.Add(new JournalEntryLine { AccountId = Guid.NewGuid(), Debit = 1000m, Credit = 0m, Position = 0 });
        entry.Lines.Add(new JournalEntryLine { AccountId = Guid.NewGuid(), Debit = 0m, Credit = 500m, Position = 1 });

        _entryRepo.Setup(r => r.GetByIdAsync(entry.Id, It.IsAny<CancellationToken>())).ReturnsAsync(entry);

        var act = () => _sut.PostAsync(entry.Id);

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "UNBALANCED_ENTRY");
    }

    [Fact]
    public async Task ShouldThrow_WhenPostingWithInsufficientLines()
    {
        var entry = new JournalEntry
        {
            Id = Guid.NewGuid(),
            EntryNumber = "JE-000003",
            Posted = false,
            CreatedAt = DateTimeOffset.UtcNow
        };
        entry.Lines.Add(new JournalEntryLine { AccountId = Guid.NewGuid(), Debit = 100m, Credit = 100m, Position = 0 });

        _entryRepo.Setup(r => r.GetByIdAsync(entry.Id, It.IsAny<CancellationToken>())).ReturnsAsync(entry);

        var act = () => _sut.PostAsync(entry.Id);

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "INSUFFICIENT_LINES");
    }

    [Fact]
    public async Task ShouldReverseEntry_WhenPosted()
    {
        var entry = CreateEntry(posted: true);
        _entryRepo.Setup(r => r.GetByIdAsync(entry.Id, It.IsAny<CancellationToken>())).ReturnsAsync(entry);
        _entryRepo.Setup(r => r.GetNextSequenceNumberAsync(It.IsAny<CancellationToken>())).ReturnsAsync(2);

        // Set up account returns for the reversal posting
        foreach (var line in entry.Lines)
        {
            _accountRepo.Setup(r => r.GetByIdAsync(line.AccountId, It.IsAny<CancellationToken>()))
                .ReturnsAsync(CreateAccount());
        }

        _entryRepo.Setup(r => r.GetByIdAsync(It.Is<Guid>(id => id != entry.Id), It.IsAny<CancellationToken>()))
            .ReturnsAsync(CreateEntry(posted: true));

        var result = await _sut.ReverseAsync(entry.Id);

        entry.Reversed.Should().BeTrue();
        _entryRepo.Verify(r => r.AddAsync(It.IsAny<JournalEntry>(), It.IsAny<CancellationToken>()), Times.Once);
        _publisher.Verify(p => p.Publish(It.IsAny<JournalEntryReversedEvent>(), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task ShouldThrow_WhenReversingUnpostedEntry()
    {
        var entry = CreateEntry(posted: false);
        _entryRepo.Setup(r => r.GetByIdAsync(entry.Id, It.IsAny<CancellationToken>())).ReturnsAsync(entry);

        var act = () => _sut.ReverseAsync(entry.Id);

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "ENTRY_NOT_POSTED");
    }

    [Fact]
    public async Task ShouldThrow_WhenDeletingPostedEntry()
    {
        var entry = CreateEntry(posted: true);
        _entryRepo.Setup(r => r.GetByIdAsync(entry.Id, It.IsAny<CancellationToken>())).ReturnsAsync(entry);

        var act = () => _sut.DeleteAsync(entry.Id);

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "ENTRY_POSTED");
    }

    [Fact]
    public async Task ShouldThrow_WhenUpdatingPostedEntry()
    {
        var entry = CreateEntry(posted: true);
        var request = new JournalEntryRequest("Update", DateOnly.FromDateTime(DateTime.UtcNow), null, null, null,
            [new JournalEntryLineRequest(Guid.NewGuid(), "test", 100m, 100m, null)]);

        _entryRepo.Setup(r => r.GetByIdAsync(entry.Id, It.IsAny<CancellationToken>())).ReturnsAsync(entry);

        var act = () => _sut.UpdateAsync(entry.Id, request);

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "ENTRY_ALREADY_POSTED");
    }
}

public class AccountServiceTests
{
    private readonly Mock<IAccountRepository> _accountRepo = new();
    private readonly Mock<ILogger<AccountService>> _logger = new();
    private readonly AccountService _sut;

    public AccountServiceTests()
    {
        _sut = new AccountService(_accountRepo.Object, _logger.Object);
    }

    [Fact]
    public async Task ShouldCreateAccount_WhenNumberUnique()
    {
        var request = new AccountRequest("1000", "Cash CHF", "Main cash account", "Asset", null, true);
        _accountRepo.Setup(r => r.GetByAccountNumberAsync("1000", It.IsAny<CancellationToken>())).ReturnsAsync((Account?)null);

        var result = await _sut.CreateAsync(request);

        result.AccountNumber.Should().Be("1000");
        result.Name.Should().Be("Cash CHF");
        result.AccountType.Should().Be("Asset");
        _accountRepo.Verify(r => r.AddAsync(It.IsAny<Account>(), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task ShouldThrow_WhenAccountNumberDuplicate()
    {
        _accountRepo.Setup(r => r.GetByAccountNumberAsync("1000", It.IsAny<CancellationToken>()))
            .ReturnsAsync(new Account { AccountNumber = "1000" });

        var act = () => _sut.CreateAsync(new AccountRequest("1000", "Dup", null, "Asset", null, true));

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "ACCOUNT_NUMBER_EXISTS");
    }

    [Fact]
    public async Task ShouldThrow_WhenSelfParent()
    {
        var id = Guid.NewGuid();
        var account = new Account { Id = id, AccountNumber = "1000", AccountType = AccountType.Asset };
        _accountRepo.Setup(r => r.GetByIdAsync(id, It.IsAny<CancellationToken>())).ReturnsAsync(account);
        _accountRepo.Setup(r => r.GetByAccountNumberAsync("1000", It.IsAny<CancellationToken>())).ReturnsAsync(account);

        var act = () => _sut.UpdateAsync(id, new AccountRequest("1000", "Cash", null, "Asset", id, true));

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "SELF_PARENT");
    }

    [Fact]
    public async Task ShouldThrow_WhenDeletingAccountWithChildren()
    {
        var account = new Account { Id = Guid.NewGuid(), AccountNumber = "1000", Balance = 0m };
        _accountRepo.Setup(r => r.GetByIdAsync(account.Id, It.IsAny<CancellationToken>())).ReturnsAsync(account);
        _accountRepo.Setup(r => r.GetChildrenAsync(account.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync([new Account { AccountNumber = "1001" }]);

        var act = () => _sut.DeleteAsync(account.Id);

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "ACCOUNT_HAS_CHILDREN");
    }

    [Fact]
    public async Task ShouldThrow_WhenDeletingAccountWithBalance()
    {
        var account = new Account { Id = Guid.NewGuid(), AccountNumber = "1000", Balance = 5000m };
        _accountRepo.Setup(r => r.GetByIdAsync(account.Id, It.IsAny<CancellationToken>())).ReturnsAsync(account);
        _accountRepo.Setup(r => r.GetChildrenAsync(account.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync([]);

        var act = () => _sut.DeleteAsync(account.Id);

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "ACCOUNT_HAS_BALANCE");
    }
}
