using FluentAssertions;
using MediatR;
using Microsoft.Extensions.Logging;
using Moq;
using SwiftApp.ERP.Modules.Sales.Application.DTOs;
using SwiftApp.ERP.Modules.Sales.Application.Services;
using SwiftApp.ERP.Modules.Sales.Domain.Entities;
using SwiftApp.ERP.Modules.Sales.Domain.Enums;
using SwiftApp.ERP.Modules.Sales.Domain.Events;
using SwiftApp.ERP.Modules.Sales.Domain.Interfaces;
using SwiftApp.ERP.SharedKernel.Domain;
using SwiftApp.ERP.SharedKernel.Exceptions;
using Xunit;

namespace SwiftApp.ERP.Modules.Sales.Tests;

public class SalesOrderServiceTests
{
    private readonly Mock<ISalesOrderRepository> _orderRepo = new();
    private readonly Mock<ISalesOrderLineRepository> _lineRepo = new();
    private readonly Mock<ICustomerRepository> _customerRepo = new();
    private readonly Mock<IPublisher> _publisher = new();
    private readonly Mock<ILogger<SalesOrderService>> _logger = new();
    private readonly SalesOrderService _sut;

    public SalesOrderServiceTests()
    {
        _sut = new SalesOrderService(_orderRepo.Object, _lineRepo.Object, _customerRepo.Object, _publisher.Object, _logger.Object);
    }

    private static Customer CreateTestCustomer() => new()
    {
        Id = Guid.NewGuid(),
        CustomerNumber = "C-2026-00001",
        CompanyName = "SwissTime AG",
        Street = "Bahnhofstrasse 10",
        City = "Zürich",
        PostalCode = "8001",
        Canton = "ZH",
        Country = "CH",
        Active = true,
        CreatedAt = DateTimeOffset.UtcNow
    };

    private static SalesOrder CreateTestOrder(Customer? customer = null, SalesOrderStatus status = SalesOrderStatus.Draft)
    {
        var c = customer ?? CreateTestCustomer();
        return new SalesOrder
        {
            Id = Guid.NewGuid(),
            OrderNumber = "SO-2026-00001",
            CustomerId = c.Id,
            Customer = c,
            Status = status,
            OrderDate = DateOnly.FromDateTime(DateTime.UtcNow),
            Currency = "CHF",
            CreatedAt = DateTimeOffset.UtcNow
        };
    }

    // ── GetByIdAsync ────────────────────────────────────────────────────

    [Fact]
    public async Task ShouldReturnOrder_WhenFoundById()
    {
        var order = CreateTestOrder();
        _orderRepo.Setup(r => r.GetByIdAsync(order.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(order);

        var result = await _sut.GetByIdAsync(order.Id);

        result.Should().NotBeNull();
        result!.OrderNumber.Should().Be("SO-2026-00001");
        result.CustomerName.Should().Be("SwissTime AG");
    }

    [Fact]
    public async Task ShouldReturnNull_WhenOrderNotFound()
    {
        _orderRepo.Setup(r => r.GetByIdAsync(It.IsAny<Guid>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((SalesOrder?)null);

        var result = await _sut.GetByIdAsync(Guid.NewGuid());

        result.Should().BeNull();
    }

    // ── CreateAsync ─────────────────────────────────────────────────────

    [Fact]
    public async Task ShouldCreateOrder_WithAutoGeneratedNumber()
    {
        var customer = CreateTestCustomer();
        var request = new SalesOrderRequest(customer.Id, null, null, "Test order", null, null, null, null, null, null);

        _customerRepo.Setup(r => r.GetByIdAsync(customer.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(customer);
        _orderRepo.Setup(r => r.GetMaxSequenceForYearAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(0);

        var result = await _sut.CreateAsync(request);

        result.OrderNumber.Should().StartWith("SO-");
        result.CustomerName.Should().Be("SwissTime AG");
        result.Status.Should().Be("Draft");
        _orderRepo.Verify(r => r.AddAsync(It.IsAny<SalesOrder>(), It.IsAny<CancellationToken>()), Times.Once);
        _publisher.Verify(p => p.Publish(It.IsAny<SalesOrderCreatedEvent>(), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task ShouldThrow_WhenCustomerNotFound()
    {
        var request = new SalesOrderRequest(Guid.NewGuid(), null, null, null, null, null, null, null, null, null);
        _customerRepo.Setup(r => r.GetByIdAsync(It.IsAny<Guid>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((Customer?)null);

        var act = () => _sut.CreateAsync(request);

        await act.Should().ThrowAsync<EntityNotFoundException>();
    }

    [Fact]
    public async Task ShouldCreateOrder_WithLines_CalculatingTotals()
    {
        var customer = CreateTestCustomer();
        var lines = new List<SalesOrderLineRequest>
        {
            new(Guid.NewGuid(), "Chronograph", 2m, 4500.00m, 0m, "Standard", null),
            new(Guid.NewGuid(), "Strap", 1m, 350.00m, 10m, "Standard", null),
        };
        var request = new SalesOrderRequest(customer.Id, null, null, null, null, null, null, null, null, lines);

        _customerRepo.Setup(r => r.GetByIdAsync(customer.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(customer);
        _orderRepo.Setup(r => r.GetMaxSequenceForYearAsync(It.IsAny<int>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(0);

        var result = await _sut.CreateAsync(request);

        // Line 1: 2 * 4500 = 9000, Line 2: 1 * 350 * 0.9 = 315. Subtotal = 9315
        result.Subtotal.Should().Be(9315.00m);
        result.Lines.Should().HaveCount(2);
    }

    // ── UpdateAsync ─────────────────────────────────────────────────────

    [Fact]
    public async Task ShouldThrow_WhenUpdatingNonDraftOrder()
    {
        var order = CreateTestOrder(status: SalesOrderStatus.Confirmed);
        _orderRepo.Setup(r => r.GetByIdAsync(order.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(order);

        var act = () => _sut.UpdateAsync(order.Id, new SalesOrderRequest(order.CustomerId, null, null, null, null, null, null, null, null, null));

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "ORDER_NOT_DRAFT");
    }

    // ── ConfirmAsync ────────────────────────────────────────────────────

    [Fact]
    public async Task ShouldConfirmOrder_WhenDraftWithLines()
    {
        var order = CreateTestOrder();
        order.Lines.Add(new SalesOrderLine
        {
            ProductId = Guid.NewGuid(),
            Quantity = 1,
            UnitPrice = 4500m,
            VatRate = VatRate.Standard,
            LineTotal = 4500m
        });
        _orderRepo.Setup(r => r.GetByIdAsync(order.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(order);

        var result = await _sut.ConfirmAsync(order.Id);

        result.Status.Should().Be("Confirmed");
        _publisher.Verify(p => p.Publish(It.IsAny<SalesOrderConfirmedEvent>(), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task ShouldThrow_WhenConfirmingNonDraftOrder()
    {
        var order = CreateTestOrder(status: SalesOrderStatus.Processing);
        _orderRepo.Setup(r => r.GetByIdAsync(order.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(order);

        var act = () => _sut.ConfirmAsync(order.Id);

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "ORDER_NOT_DRAFT");
    }

    [Fact]
    public async Task ShouldThrow_WhenConfirmingOrderWithNoLines()
    {
        var order = CreateTestOrder();
        _orderRepo.Setup(r => r.GetByIdAsync(order.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(order);

        var act = () => _sut.ConfirmAsync(order.Id);

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "ORDER_NO_LINES");
    }

    // ── AdvanceStatusAsync ──────────────────────────────────────────────

    [Theory]
    [InlineData(SalesOrderStatus.Confirmed, "Processing")]
    [InlineData(SalesOrderStatus.Processing, "Shipped")]
    [InlineData(SalesOrderStatus.Shipped, "Delivered")]
    [InlineData(SalesOrderStatus.Delivered, "Completed")]
    public async Task ShouldAdvanceStatus_WhenValidTransition(SalesOrderStatus from, string expectedTo)
    {
        var order = CreateTestOrder(status: from);
        _orderRepo.Setup(r => r.GetByIdAsync(order.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(order);

        var result = await _sut.AdvanceStatusAsync(order.Id);

        result.Status.Should().Be(expectedTo);
    }

    [Theory]
    [InlineData(SalesOrderStatus.Draft)]
    [InlineData(SalesOrderStatus.Completed)]
    [InlineData(SalesOrderStatus.Cancelled)]
    public async Task ShouldThrow_WhenCannotAdvanceStatus(SalesOrderStatus status)
    {
        var order = CreateTestOrder(status: status);
        _orderRepo.Setup(r => r.GetByIdAsync(order.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(order);

        var act = () => _sut.AdvanceStatusAsync(order.Id);

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "INVALID_STATUS_TRANSITION");
    }

    // ── CancelAsync ─────────────────────────────────────────────────────

    [Fact]
    public async Task ShouldCancelOrder_WhenStatusAllows()
    {
        var order = CreateTestOrder(status: SalesOrderStatus.Confirmed);
        _orderRepo.Setup(r => r.GetByIdAsync(order.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(order);

        var result = await _sut.CancelAsync(order.Id, "Customer requested");

        result.Status.Should().Be("Cancelled");
        _publisher.Verify(p => p.Publish(It.IsAny<SalesOrderCancelledEvent>(), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Theory]
    [InlineData(SalesOrderStatus.Completed)]
    [InlineData(SalesOrderStatus.Cancelled)]
    public async Task ShouldThrow_WhenCancellingCompletedOrCancelled(SalesOrderStatus status)
    {
        var order = CreateTestOrder(status: status);
        _orderRepo.Setup(r => r.GetByIdAsync(order.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(order);

        var act = () => _sut.CancelAsync(order.Id, "reason");

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "ORDER_CANNOT_CANCEL");
    }

    // ── DeleteAsync ─────────────────────────────────────────────────────

    [Theory]
    [InlineData(SalesOrderStatus.Draft)]
    [InlineData(SalesOrderStatus.Cancelled)]
    public async Task ShouldDeleteOrder_WhenDraftOrCancelled(SalesOrderStatus status)
    {
        var order = CreateTestOrder(status: status);
        _orderRepo.Setup(r => r.GetByIdAsync(order.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(order);

        await _sut.DeleteAsync(order.Id);

        _orderRepo.Verify(r => r.SoftDeleteAsync(order.Id, It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task ShouldThrow_WhenDeletingActiveOrder()
    {
        var order = CreateTestOrder(status: SalesOrderStatus.Processing);
        _orderRepo.Setup(r => r.GetByIdAsync(order.Id, It.IsAny<CancellationToken>()))
            .ReturnsAsync(order);

        var act = () => _sut.DeleteAsync(order.Id);

        await act.Should().ThrowAsync<BusinessRuleException>()
            .Where(e => e.Rule == "ORDER_CANNOT_DELETE");
    }
}
